version: '3.1'
services:
  webhook:
    image: webdevops/apache:latest
    depends_on:
      - php7
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    environment:
      WEB_PHP_SOCKET: "php7:9000"
      WEB_DOCUMENT_ROOT: "/var/www/html"
  php7:
    build: ./.docker/php7
    restart: always
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
    depends_on:
      - memcached
      - postgres
  memcached:
    build: ./.docker/memcached
    env_file:
      - .env
  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_DB: botadmin
      POSTGRES_USER: botadmin
      POSTGRES_PASSWORD: botadmin
    ports:
      - 5432
    volumes:
      - ./.docker/database/data:/var/lib/postgresql/data
