version: '3.1'
services:
  webhook:
    image: webdevops/apache:latest
    depends_on:
      - php7
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    environment:
      WEB_PHP_SOCKET: "php7:9000"
      WEB_DOCUMENT_ROOT: "/var/www/html"
  php7:
    build: ./.docker/php7
    restart: always
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
